#!/bin/bash
# ubuntu-2604-debloat.sh
# Universal Ubuntu 26.04 LTS GNOME 50 Debloat Script
# Removes snap, flatpak, Ubuntu bloat, GNOME bloat; pins to prevent reinstall
# Installs GNOME Extension Manager; hides unremovable apps
# No user-specific apps (IDE, browser, terminal) installed
# Tested on Ubuntu 26.04 LTS (resolute) with GNOME 50, kernel 7.x
# Run as root: sudo ./ubuntu-2604-debloat.sh [--yes] [--dry-run] [--verbose]

set -euo pipefail

# ============================================================================
# CONFIGURATION & GLOBALS
# ============================================================================
SCRIPT_NAME="ubuntu-2604-debloat"
VERSION="1.0.0"
DRY_RUN=false
VERBOSE=false
AUTO_YES=false
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
ROLLBACK_DIR="/tmp/ubuntu-debloat-rollback-${TIMESTAMP}"
LOG_FILE="${ROLLBACK_DIR}/debloat.log"
APT_PREFS_BACKUP="${ROLLBACK_DIR}/apt-prefs-backup"
INSTALLED_PKGS_FILE="${ROLLBACK_DIR}/installed-packages.txt"
APT_PREFS_DIR="/etc/apt/preferences.d"
BACKUP_APT_PREFS_DIR="${ROLLBACK_DIR}/apt-prefs.d.backup"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================
log() { echo -e "${BLUE}[$(date '+%H:%M:%S')]${NC} $*" | tee -a "$LOG_FILE"; }
info() { echo -e "${GREEN}[INFO]${NC} $*" | tee -a "$LOG_FILE"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*" | tee -a "$LOG_FILE"; }
error() { echo -e "${RED}[ERROR]${NC} $*" | tee -a "$LOG_FILE"; }
die() { error "$*"; exit 1; }

run() {
    if [[ "$DRY_RUN" == true ]]; then
        info "[DRY-RUN] $*"
    else
        eval "$@" 2>&1 | tee -a "$LOG_FILE"
    fi
}

apt_install() { run "apt install -y $*"; }
apt_remove() { run "apt remove --purge -y $*"; }
apt_update() { run "apt update"; }

is_installed() { dpkg -l | grep -q "^ii  $1 "; }

# ============================================================================
# PRE-FLIGHT CHECKS
# ============================================================================
check_root() {
    [[ $EUID -eq 0 ]] || die "Must run as root. Use: sudo $0"
}

check_ubuntu_version() {
    local version
    version=$(lsb_release -rs 2>/dev/null || echo "unknown")
    [[ "$version" == "26.04" ]] || die "This script requires Ubuntu 26.04 LTS. Found: $version"
}

check_gnome_version() {
    local version
    version=$(gnome-shell --version 2>/dev/null | grep -oE '[0-9]+' | head -1 || echo "0")
    [[ "$version" -ge 50 ]] || die "This script requires GNOME 50+. Found: $version"
}

check_kernel_version() {
    local major
    major=$(uname -r | cut -d. -f1)
    [[ "$major" -ge 7 ]] || warn "Kernel major version < 7 (found: $major). Proceeding anyway."
}

# ============================================================================
# BACKUP & ROLLBACK SETUP
# ============================================================================
setup_rollback() {
    mkdir -p "$ROLLBACK_DIR" "$BACKUP_APT_PREFS_DIR"
    touch "$LOG_FILE"
    chmod 644 "$LOG_FILE"

    # Backup apt preferences
    [[ -d "$APT_PREFS_DIR" ]] && cp -r "$APT_PREFS_DIR" "$BACKUP_APT_PREFS_DIR"

    # Record installed packages
    dpkg -l | grep '^ii' > "$INSTALLED_PKGS_FILE"

    # Create rollback script
    cat > "${ROLLBACK_DIR}/rollback.sh" << 'ROLLBACK_EOF'
#!/bin/bash
# Rollback script generated by ubuntu-2604-debloat.sh
set -euo pipefail

ROLLBACK_DIR="$(dirname "$0")"
APT_PREFS_DIR="/etc/apt/preferences.d"
BACKUP_DIR="${ROLLBACK_DIR}/apt-prefs.d.backup"
LOG_FILE="${ROLLBACK_DIR}/debloat.log"

echo "[ROLLBACK] Restoring apt preferences..."
rm -rf "$APT_PREFS_DIR"
cp -r "$BACKUP_DIR" "$APT_PREFS_DIR"

echo "[ROLLBACK] Restoring packages from backup..."
# Note: This only restores apt config. Package reinstallation must be manual.
echo "[ROLLBACK] Apt preferences restored. Run 'apt update' and reinstall packages manually if needed."
ROLLBACK_EOF
    chmod +x "${ROLLBACK_DIR}/rollback.sh"

    info "Rollback script created at ${ROLLBACK_DIR}/rollback.sh"
    info "Backup stored in ${ROLLBACK_DIR}"
}

# ============================================================================
# PHASE 1: SNAP REMOVAL & PINNING
# ============================================================================
remove_snap() {
    info "Phase: Removing Snap..."

    # Stop and disable snap services
    run "systemctl stop snapd.service snapd.socket snapd.apparmor.service 2>/dev/null || true"
    run "systemctl disable snapd.service snapd.socket snapd.apparmor.service 2>/dev/null || true"

    # Remove all snaps
    if command -v snap &>/dev/null; then
        snap list --all 2>/dev/null | awk '/disabled/{print $1, $3}' | while read -r snapname revision; do
            [[ -n "$snapname" && -n "$revision" ]] && run "snap remove \"$snapname\" --revision=\"$revision\""
        done
    fi

    # Remove snapd package
    if is_installed snapd; then
        apt_remove snapd
    fi

    # Clean snap directories
    run "rm -rf /snap /var/snap /var/lib/snapd /var/cache/snapd /home/*/snap 2>/dev/null || true"
    info "Snap removed and cleaned."
}

pin_snap() {
    info "Phase: Pinning Snap to prevent reinstall..."
    cat > /etc/apt/preferences.d/99-block-snap << 'EOF'
# Block Snap permanently
Package: snapd
Pin: release *
Pin-Priority: -1

Package: snap-confine
Pin: release *
Pin-Priority: -1

Package: snapd-glib
Pin: release *
Pin-Priority: -1

Package: gir1.2-snapd-2
Pin: release *
Pin-Priority: -1

Package: libsnapd-glib*
Pin: release *
Pin-Priority: -1
EOF
    info "Snap pinned (Pin-Priority: -1)."
}

# ============================================================================
# PHASE 2: FLATPAK REMOVAL & PINNING
# ============================================================================
remove_flatpak() {
    info "Phase: Removing Flatpak..."
    if is_installed flatpak; then
        apt_remove flatpak
    fi
    run "rm -rf /var/lib/flatpak /home/*/.local/share/flatpak /var/lib/flatpak 2>/dev/null || true"
    info "Flatpak removed."
}

pin_flatpak() {
    info "Phase: Pinning Flatpak to prevent reinstall..."
    cat > /etc/apt/preferences.d/99-block-flatpak << 'EOF'
# Block Flatpak permanently
Package: flatpak
Pin: release *
Pin-Priority: -1

Package: flatpak-builder
Pin: release *
Pin-Priority: -1

Package: libflatpak*
Pin: release *
Pin-Priority: -1

Package: libostree*
Pin: release *
Pin-Priority: -1
EOF
    info "Flatpak pinned (Pin-Priority: -1)."
}

# ============================================================================
# PHASE 3: UBUNTU GNOME EXTENSIONS REMOVAL & PINNING
# ============================================================================
remove_ubuntu_extensions() {
    info "Phase: Removing Ubuntu GNOME Extensions..."
    if is_installed gnome-shell-ubuntu-extensions; then
        apt_remove gnome-shell-ubuntu-extensions
    else
        info "gnome-shell-ubuntu-extensions not installed."
    fi
}

pin_ubuntu_extensions() {
    info "Phase: Pinning Ubuntu GNOME Extensions..."
    cat > /etc/apt/preferences.d/99-block-ubuntu-extensions << 'EOF'
# Block Ubuntu GNOME Extensions permanently
Package: gnome-shell-ubuntu-extensions
Pin: release *
Pin-Priority: -1
EOF
    info "Ubuntu GNOME Extensions pinned."
}

# ============================================================================
# PHASE 4: INSTALL GNOME EXTENSION MANAGER
# ============================================================================
install_extension_manager() {
    info "Phase: Installing GNOME Extension Manager..."
    apt_update
    if is_installed gnome-shell-extension-manager; then
        info "gnome-shell-extension-manager already installed."
    else
        apt_install gnome-shell-extension-manager
    fi
}

# ============================================================================
# PHASE 5: REMOVE GNOME BLOAT APPS
# ============================================================================
remove_gnome_bloat() {
    info "Phase: Removing GNOME bloat apps..."

    # Apps that can be safely removed (no critical deps)
    local bloat_packages=(
        # Core GNOME apps
        gnome-calculator gnome-characters gnome-clocks gnome-logs
        gnome-weather gnome-maps gnome-music gnome gnome-photos
        gnome-contacts gnome-calendar gnome-font-viewer
        gnome-text-editor gnome-system-monitor gnome-disk-utility
        gnome-terminal gnome-console gnome-font-viewer gnome-text-editor
        
        # Media
        totem rhythmbox cheese simple-scan
        
        # Utilities
        baobab seahorse
        
        # Games
        gnome-mahjongg gnome-mines gnome-sudoku gnome-taquin gnome-nibbles
        gnome-robots gnome-tetravex five-or-more four-in-a-row hitori
        lightsoff quadrapassel swell-foop tali
        
        # Developer tools (if present)
        gnome-builder gnome-code-assistance
    )

    for pkg in "${bloat_packages[@]}"; do
        if is_installed "$pkg"; then
            apt_remove "$pkg"
        else
            [[ "$VERBOSE" == true ]] && info "$pkg not installed, skipping."
        fi
    done

    # Remove orphaned dependencies
    run "apt autoremove --purge -y"
    info "GNOME bloat apps removed."
}

# ============================================================================
# PHASE 6: HIDE UNREMOVABLE GNOME APPS
# ============================================================================
hide_unremovable_apps() {
    info "Phase: Hiding unremovable GNOME apps..."

    # Apps that can't be removed (dependencies) but should be hidden
    local hide_apps=(
        "org.gnome.Yelp.desktop"
        "gnome-language-selector.desktop"
        "nm-connection-editor.desktop"
    )

    # System-wide hide (requires root)
    for desktop in "${hide_apps[@]}"; do
        local src="/usr/share/applications/$desktop"
        if [[ -f "$src" ]]; then
            cp "$src" "${src}.bak"
            sed -i '/^\[Desktop Entry\]/a NoDisplay=true' "$src"
            info "Hidden (system): $desktop"
        fi
    done

    # User-specific hide (for current user)
    local user_home="${SUDO_HOME:-$HOME}"
    local user_apps_dir="$user_home/.local/share/applications"
    mkdir -p "$user_apps_dir"

    for desktop in "${hide_apps[@]}"; do
        local src="/usr/share/applications/$desktop"
        if [[ -f "$src" ]]; then
            cp "$src" "$user_apps_dir/"
            sed -i '/^\[Desktop Entry\]/a NoDisplay=true' "$user_apps_dir/$desktop"
            info "Hidden (user): $desktop"
        fi
    done

    info "Unremovable apps hidden via NoDisplay=true."
}

# ============================================================================
# PHASE 7: REMOVE UBUNTU BLOAT PACKAGES
# ============================================================================
remove_ubuntu_bloat() {
    info "Phase: Removing Ubuntu bloat packages..."

    local ubuntu_bloat=(
        # Metapackages
        ubuntu-desktop-minimal ubuntu-desktop ubuntu-session ubuntu-settings
        # Branding
        ubuntu-wallpapers ubuntu-wallpapers-resolute ubuntu-docs
        # Ubuntu Pro / Advantage
        ubuntu-pro-client ubuntu-pro-client-l10n ubuntu-advantage-desktop-daemon ubuntu-advantage-tools
        # Release upgraders
        ubuntu-release-upgrader-gtk ubuntu-release-upgrader-core
        # Telemetry
        ubuntu-report ubuntu-advantage-desktop-daemon
        # Update management
        update-manager update-notifier update-notifier-common unattended-upgrades
        # Drivers
        ubuntu-drivers-common
        # Setup/Tour
        gnome-initial-setup gnome-tour
        # Software centers
        gnome-software snap-store
        # Software properties
        software-properties-gtk software-properties-common
        # Firmware
        fwupd fwupd-signed
        # Kernel
        ubuntu-kernel-accessories
        # Keys
        ubuntu-keyring
        # Plymouth
        plymouth-theme-ubuntu-text
    )

    for pkg in "${ubuntu_bloat[@]}"; do
        if is_installed "$pkg"; then
            apt_remove "$pkg"
        else
            [[ "$VERBOSE" == true ]] && info "$pkg not installed."
        fi
    done

    run "apt autoremove --purge -y"
    info "Ubuntu bloat packages removed."
}

# ============================================================================
# PHASE 8: PIN ALL UBUNTU & GNOME BLOAT
# ============================================================================
pin_all_bloat() {
    info "Phase: Pinning all bloat packages to prevent reinstall..."

    cat > /etc/apt/preferences.d/99-block-ubuntu-bloat << 'EOF'
# Block Ubuntu bloat packages permanently
Package: ubuntu-desktop*
Pin: release *
Pin-Priority: -1

Package: ubuntu-session
Pin: release *
Pin-Priority: -1

Package: ubuntu-settings
Pin: release *
Pin-Priority: -1

Package: ubuntu-wallpapers*
Pin: release *
Pin-Priority: -1

Package: ubuntu-docs
Pin: release *
Pin-Priority: -1

Package: ubuntu-pro-client*
Pin: release *
Pin-Priority: -1

Package: ubuntu-release-upgrader*
Pin: release *
Pin-Priority: -1

Package: ubuntu-report
Pin: release *
Pin-Priority: -1

Package: ubuntu-advantage-desktop-daemon
Pin: release *
Pin-Priority: -1

Package: update-manager*
Pin: release *
Pin-Priority: -1

Package: update-notifier*
Pin: release *
Pin-Priority: -1

Package: unattended-upgrades
Pin: release *
Pin-Priority: -1

Package: ubuntu-drivers-common
Pin: release *
Pin-Priority: -1

Package: gnome-initial-setup
Pin: release *
Pin-Priority: -1

Package: gnome-tour
Pin: release *
Pin-Priority: -1

Package: gnome-software
Pin: release *
Pin-Priority: -1

Package: snap-store
Pin: release *
Pin-Priority: -1

Package: software-properties-gtk
Pin: release *
Pin-Priority: -1

Package: software-properties-common
Pin: release *
Pin-Priority: -1

Package: fwupd
Pin: release *
Pin-Priority: -1

Package: fwupd-signed
Pin: release *
Pin-Priority: -1

Package: ubuntu-advantage-tools
Pin: release *
Pin-Priority: -1

Package: ubuntu-kernel-accessories
Pin: release *
Pin-Priority: -1

Package: ubuntu-keyring
Pin: release *
Pin-Priority: -1

Package: plymouth-theme-ubuntu-text
Pin: release *
Pin-Priority: -1

Package: gnome-shell-ubuntu-extensions
Pin: release *
Pin-Priority: -1

Package: gnome-initial-setup
Pin: release *
Pin-Priority: -1

Package: gnome-tour
Pin: release *
Pin-Priority: -1

# GNOME bloat apps
Package: baobab
Pin: release *
Pin-Priority: -1

Package: gnome-calculator
Pin: release *
Pin-Priority: -1

Package: gnome-characters
Pin: release *
Pin-Priority: -1

Package: gnome-clocks
Pin: release *
Pin-Priority: -1

Package: gnome-disk-utility
Pin: release *
Pin-Priority: -1

Package: gnome-font-viewer
Pin: release *
Pin-Priority: -1

Package: gnome-logs
Pin: release *
Pin-Priority: -1

Package: gnome-text-editor
Pin: release *
Pin-Priority: -1

Package: gnome-calendar
Pin: release *
Pin-Priority: -1

Package: gnome-contacts
Pin: release *
Pin-Priority: -1

Package: gnome-maps
Pin: release *
Pin-Priority: -1

Package: gnome-weather
Pin: release *
Pin-Priority: -1

Package: gnome-music
Pin: release *
Pin-Priority: -1

Package: gnome-photos
Pin: release *
Pin-Priority: -1

Package: totem
Pin: release *
Pin-Priority: -1

Package: rhythmbox
Pin: release *
Pin-Priority: -1

Package: cheese
Pin: release *
Pin-Priority: -1

Package: simple-scan
Pin: release *
Pin-Priority: -1

Package: seahorse
Pin: release *
Pin-Priority: -1

Package: gnome-system-monitor
Pin: release *
Pin-Priority: -1

Package: gnome-terminal
Pin: release *
Pin-Priority: -1

Package: gnome-console
Pin: release *
Pin-Priority: -1

Package: kgx
Pin: release *
Pin-Priority: -1

Package: tilix
Pin: release *
Pin-Priority: -1

Package: terminator
Pin: release *
Pin-Priority: -1

Package: konsole
Pin: release *
Pin-Priority: -1

Package: kitty
Pin: release *
Pin-Priority: -1

Package: warp-terminal
Pin: release *
Pin-Priority: -1
EOF

    # Also hold packages via apt-mark
    local hold_packages=(
        gnome-shell-ubuntu-extensions snapd ubuntu-advantage-desktop-daemon
        ubuntu-desktop ubuntu-desktop-minimal ubuntu-docs
        ubuntu-drivers-common ubuntu-minimal ubuntu-pro-client
        ubuntu-pro-client-l10n ubuntu-release-upgrader-core
        ubuntu-release-upgrader-gtk ubuntu-report ubuntu-session
        ubuntu-settings unattended-upgrades update-manager
        update-notifier update-notifier-common
    )
    for pkg in "${hold_packages[@]}"; do
        run "apt-mark hold $pkg 2>/dev/null || true"
    done

    info "All bloat packages pinned and held."
}

# ============================================================================
# PHASE 9: CLEANUP
# ============================================================================
cleanup() {
    info "Phase: Cleaning up..."
    run "apt autoremove --purge -y"
    run "apt clean"
    run "apt autoclean"
    info "Cleanup complete."
}

# ============================================================================
# VERIFICATION
# ============================================================================
verify() {
    info "Phase: Verifying installation..."

    local failed=0

    # Check snap removed
    if command -v snap &>/dev/null; then
        warn "snap command still exists"
        ((failed++))
    else
        info "✓ snap removed"
    fi

    # Check flatpak removed
    if command -v flatpak &>/dev/null; then
        warn "flatpak command still exists"
        ((failed++))
    else
        info "✓ flatpak removed"
    fi

    # Check Ubuntu extensions removed
    if is_installed gnome-shell-ubuntu-extensions; then
        warn "gnome-shell-ubuntu-extensions still installed"
        ((failed++))
    else
        info "✓ Ubuntu GNOME Extensions removed"
    fi

    # Check Extension Manager installed
    if is_installed gnome-shell-extension-manager; then
        info "✓ GNOME Extension Manager installed"
    else
        warn "gnome-shell-extension-manager not installed"
        ((failed++))
    fi

    # Check pinned packages
    local pinned_count
    pinned_count=$(grep -r "Pin-Priority: -1" /etc/apt/preferences.d/ 2>/dev/null | wc -l)
    info "✓ $pinned_count packages pinned"

    # Check held packages
    local held_count
    held_count=$(apt-mark showhold 2>/dev/null | wc -l)
    info "✓ $held_count packages held"

    if [[ $failed -eq 0 ]]; then
        info "All verifications passed!"
    else
        warn "$failed verification(s) failed"
    fi
}

# ============================================================================
# USAGE / HELP
# ============================================================================
usage() {
    cat << EOF
Usage: sudo $0 [OPTIONS]

Universal Ubuntu 26.04 LTS GNOME 50 Debloat Script

OPTIONS:
    --yes              Non-interactive mode (auto-yes to all prompts)
    --dry-run          Show what would be done without executing
    --verbose          Verbose output
    --restore          Run rollback script from last run
    --help             Show this help
    --version          Show version

EXAMPLES:
    sudo $0                    # Interactive mode
    sudo $0 --yes              # Fully automated
    sudo $0 --dry-run --verbose # Preview changes
    sudo $0 --restore          # Rollback last run

REQUIREMENTS:
    - Ubuntu 26.04 LTS (resolute)
    - GNOME 50+
    - Linux kernel 7.x
    - Root privileges

WHAT THIS SCRIPT DOES:
  1. Removes snap completely and pins to prevent reinstall
  2. Removes flatpak and pins to prevent reinstall
  3. Removes Ubuntu GNOME extensions and pins
  4. Installs GNOME Extension Manager (native apt)
  4. Removes GNOME bloat apps (calculator, weather, maps, games, etc.)
  5. Hides unremovable apps (Help, Language Support, Network Config)
  6. Removes Ubuntu bloat (metapackages, telemetry, software centers, etc.)
  8. Pins ALL bloat packages to prevent reinstall on updates
  9. Holds packages via apt-mark hold

WHAT THIS SCRIPT DOES NOT DO:
  ✗ Install any IDE (VS Code, JetBrains, etc.)
  ✗ Install any browser (Chrome, Firefox, etc.)
  ✗ Install any terminal (Ghostty, Kitty, etc.)
  ✗ Install any user-specific tools
  ✗ Modify user configs or dotfiles

ROLLBACK:
  Run 'sudo /tmp/ubuntu-debloat-rollback-<timestamp>/rollback.sh'
  or use --restore flag (if implemented)

EOF
}

# ============================================================================
# MAIN
# ============================================================================
parse_args() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            --yes) AUTO_YES=true ;;
            --dry-run) DRY_RUN=true ;;
            --verbose) VERBOSE=true ;;
            --restore)
                local latest_rollback
                latest_rollback=$(ls -dt /tmp/ubuntu-debloat-rollback-* 2>/dev/null | head -1)
                [[ -n "$latest_rollback" ]] || die "No rollback found"
                bash "$latest_rollback/rollback.sh"
                exit 0
                ;;
            --help) usage; exit 0 ;;
            --version) echo "$SCRIPT_NAME v$VERSION"; exit 0 ;;
            *) die "Unknown option: $1. Use --help." ;;
        esac
        shift
    done
}

main() {
    parse_args "$@"

    # Pre-flight
    check_root
    check_ubuntu_version
    check_gnome_version
    check_kernel_version

    setup_rollback

    info "Starting $SCRIPT_NAME v$VERSION"
    info "Target: Ubuntu 26.04 LTS, GNOME 50, Kernel 7.x"
    [[ "$DRY_RUN" == true ]] && warn "DRY-RUN MODE - No changes will be made"

    apt_update

    # Execute phases
    remove_snap
    pin_snap

    remove_flatpak
    pin_flatpak

    remove_ubuntu_extensions
    pin_ubuntu_extensions

    install_extension_manager

    remove_gnome_bloat
    hide_unremovable_apps

    remove_ubuntu_bloat
    pin_all_bloat

    cleanup
    verify

    info "Debloat complete! Rollback available at: ${ROLLBACK_DIR}/rollback.sh"
    info "Log file: ${LOG_FILE}"
}

main "$@"
